package url.shortener.makeitshort.models;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "urls", indexes = {
        @Index(columnList = "id", name = "url_id"),
        @Index(columnList = "code", name = "code")
})
public class Url {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    Long id;

    /**
     * Code generated by selected engine, indexed for faster lookup
     */
    @Column(unique = true)
    String code;

    @Column(length=1000, nullable = false)
    String realUrl;

}


